spring:
  mail:
    password: test
    username: test@test.com
    host: test.test.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://portfolio-mysql:3306/portfolio?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
cookie:
  domain: "api.app.localhost"
cors:
  origin: "*"
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: "DEBUG"
