version: "3.9"

services:
  portfolio-frontend:
    container_name: portfolio-frontend
    image: portfolio-frontend:latest
    ports:
      - "80:80"
    networks:
      - portfolio
    depends_on:
      - portfolio-backend
  portfolio-backend:
    container_name: portfolio-backend
    image: portfolio-backend:latest
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - portfolio
    depends_on:
      portfolio-mysql:
        condition: service_healthy
  portfolio-mysql:
    container_name: portfolio-mysql
    image: mysql:8
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - portfolio
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
networks:
  portfolio:
    driver: bridge
    name: portfolio
    ipam:
      config:
        - subnet: 172.16.57.0/24

